language: ruby
cache: bundler
rvm:
- 2.4.2
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rspec spec
addons:
  postgresql: '9.6'
  code_climate:
    repo_token: 6acb3ae469a533292083b76b2b5a27796f7ee25e9c6cdfbf81e99621047b7977
bundler_args: "--without production"
sudo: false
